### ISSUE TITLE
The status of InstantBird

### ISSUE THREAD

**Issue by maliayas** [instantbird/blog.instantbird.org#1]
Hello @clokep,

I got a little bit excited when I saw your latest commits on this repo by chance.  Are there any plans to revive InstantBird for people who wants a standalone app?

I remember the good old days when I used to use MSN from IB and follow IB development on IRC :) Now everybody uses WhatsApp and InstantBird would be a good client for it (if the company allows this)

**Comment by maliayas** [comment]
Thanks very much for everything you and the team have done so far.

**Comment by clokep** [comment]
Thanks for your interest, but no, there are no plans to continue working on Instantbird. We are just trying to shut-down some infrastructure, but didn't want to lose some of the content (e.g. the blog).

The contents of Florian's blogpost from 2017 are still true: http://blog.queze.net/post/2017/10/18/Thunderbird-is-the-next-version-of-Instantbird (although I'm not really sure why we didn't post that on the Instantbird blog too...)

**Comment by Neustradamus** [comment]
@clokep: It is possible to publish an article to inform people that InstandBird is now Mozilla Thunderbird?

Nothing here:
- https://blog.instantbird.org/

And https://instantbird.org/ and https://www.instantbird.org/ are not redirected to the blog or the GitHub:
- https://github.com/instantbird/

Thanks in advance.
